.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
* Updates README
* Moves documentation related to Github to .github
*Documentation
No tests required.
- [ X ] My PR follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code or materials
=> docs: updated README and added PR Template

package.json
After npm install is executed, Heroku installs front-end dependencies and builds the front-end.
Relates to #73
- Code
=> other: allows Continuous Delivery through Heroku

angular-src/src/app/app.module.ts, angular-src/src/app/general/about-us/about-us.component.css, angular-src/src/app/general/about-us/about-us.component.html, angular-src/src/app/general/about-us/about-us.component.spec.ts, angular-src/src/app/general/about-us/about-us.component.ts, angular-src/src/app/general/home/home.component.html
Create Simple About Us page describing who we are and what we do.
Fixes #40
=> feat: Create New About Us Page

server/routes/student-routes.js
Allows teachers and alumni to login
=> feat: allows teachers and alumni to login

angular-src/package-lock.json, angular-src/package.json, package-lock.json
other: updates dependencies, in order to leverage the production app
=> other: updates dependencies, in order to leverage the production app

angular-src/src/app/general/navbar/navbar.component.ts, server/routes/utils-routes.js
=> fix: fixes nav-bar Perfil bug

angular-src/src/app/general/gce-thesis/filter-results.pipe.ts, angular-src/src/app/general/gce-thesis/gce-thesis.component.css, angular-src/src/app/general/gce-thesis/gce-thesis.component.html, angular-src/src/app/general/gce-thesis/gce-thesis.component.ts, angular-src/src/app/services/thesis.service.ts
=> feat: shows available theses

angular-src/src/app/app.module.ts, angular-src/src/app/general/gce-thesis/filter-results.pipe.ts
=> fix: fixes bug in filter results

angular-src/package-lock.json, angular-src/src/app/app.component.ts, angular-src/src/app/app.module.ts, angular-src/src/app/general/gce-hash-code-next/gce-hash-code-next.component.css, angular-src/src/app/general/gce-hash-code-next/gce-hash-code-next.component.html, angular-src/src/app/general/gce-hash-code-program/gce-hash-code-program.component.css, angular-src/src/app/general/gce-hash-code-program/gce-hash-code-program.component.html, angular-src/src/app/general/gce-hash-code/gce-hash-code.component.css, angular-src/src/app/general/gce-hash-code/gce-hash-code.component.html, angular-src/src/app/general/home/home.component.css, angular-src/src/app/general/home/home.component.html, angular-src/src/app/general/login/login.component.css, angular-src/src/app/general/navbar/navbar.component.css, angular-src/src/app/general/navbar/navbar.component.html, angular-src/src/app/general/navbar/navbar.component.ts, angular-src/src/app/user-student/student-profile/student-profile.component.css, config/db.js, package-lock.json, server/routes/utils-routes.js
=> Added hashcode signup and some interface changes

angular-src/src/app/general/gce-hash-code/gce-hash-code.component.ts
=> Heroku bugfix

config/db.js, prepare_env_windows.bat
=> Fixing security breaches

angular-src/src/app/general/gce-hash-code-program/gce-hash-code-program.component.html, angular-src/src/app/general/home/home.component.html
=> feat:hashcode update; home update

angular-src/src/app/general/gce-hash-code-program/gce-hash-code-program.component.html
=> fix: removed link from hashcode signup

.env.example, .gitignore, README.md, angular-src/scripts/set-env.env.example, angular-src/scripts/set-env.ts, config/db.js, gce_base.js
Updates the setting up process - now it is easier to configure env. variables
=> improvements

angular-src/src/app/general/chat/chat-dialog/chat-dialog.component.css, angular-src/src/app/general/chat/chat-dialog/chat-dialog.component.html, angular-src/src/app/general/chat/chat-dialog/chat-dialog.component.ts, angular-src/src/app/general/chat/chat.service.ts, angular-src/src/app/general/gce-thesis/filter-results.pipe.ts, angular-src/src/app/general/gce-thesis/gce-thesis.component.html, angular-src/src/app/general/gce-thesis/gce-thesis.component.ts, angular-src/src/app/services/thesis.service.ts, package-lock.json, package.json, server/routes/chatbot-routes.js
chatbot now redirects to gce-thesis
two different views on gce-thesis
=> Chatbot improvements

angular-src/src/app/general/chat/chat-dialog/chat-dialog.component.html, angular-src/src/app/general/chat/chat-dialog/chat-dialog.component.ts, angular-src/src/app/general/chat/chat.service.ts, gce_base.js, server/services/chatbot-services.js
=> Classifier improvements

angular-src/src/app/general/chat/chat.service.ts, angular-src/src/app/general/gce-thesis/areas-dump.ts, angular-src/src/app/general/gce-thesis/gce-thesis.component.html, angular-src/src/app/general/gce-thesis/gce-thesis.component.ts, angular-src/src/app/services/thesis.service.ts, server/routes/chatbot-routes.js, server/routes/theses-routes.js, server/routes/utils-routes.js
=> Gce thesis frontend

README.md, gce_base.js
=> Backend improvements

server/routes/theses-routes.js, server/services/theses-modules/MEIC_3.js, server/services/theses-services.js
=> feat: improvements to classifier MEIC_3

angular-src/src/app/general/gce-thesis/gce-thesis.component.ts, angular-src/src/app/general/partners-carousel/partners-carousel.component.html
=> Frontend fix

angular-src/src/app/general/gce-thesis/gce-thesis.component.ts
=> fix: fix gce-thesis view

angular-src/src/index.html
=> Webapp Image Preview

server/routes/theses-routes.js, server/services/student-services.js
=> fix: DEI teacher's support

angular-src/package-lock.json, angular-src/src/app/app.module.ts, angular-src/src/app/general/gce-articles-pinned/gce-articles-pinned.component.css, angular-src/src/app/general/gce-articles-pinned/gce-articles-pinned.component.html, angular-src/src/app/general/gce-articles-pinned/gce-articles-pinned.component.ts, angular-src/src/app/general/gce-articles/gce-articles.component.css, angular-src/src/app/general/gce-articles/gce-articles.component.html, angular-src/src/app/general/gce-articles/gce-articles.component.ts, angular-src/src/app/services/articles.service.spec.ts, angular-src/src/app/services/articles.service.ts, package-lock.json, package.json, server/routes.js, server/routes/articles-routes.js, server/services/articles-services.js
Retrieve and display Medium articles. UI improvements: articles by type, pinned article, publication date.
Fixes #218 
Fixes #219
- Code
- This change requires a documentation update
- New feature
Co-authored-by: @danielsantosfernandes
=> enhance Inside View #218 #219

angular-src/package-lock.json, package-lock.json
An error was occurring during `npm run first setup` due to previous package update and changes.
=> fix: build error

angular-src/src/app/general/footer/footer.component.css, angular-src/src/app/general/footer/footer.component.html
=> fix: footer

angular-src/src/app/general/footer/footer.component.css, angular-src/src/app/general/footer/footer.component.html, angular-src/src/app/general/home/home.component.css
- Add Instagram icon
- Update copyright date
- Add links for our mission and team
Fixes #247 
- Code
=> Enhance Footer
